<?php
/**
 * @file WDG Support Monitor
 * @author Web Development Group (WDG) <https://www.webdevelopmentgroup.com>
 */

/**
 * Implements hook_cron().
 */
function wdg_support_monitor_cron() {
  $frequency = 60 * 60 * 12; // 12 hours

  $last_run = WDG_Support_Monitor::get_instance()->get_last_run();
  if ( is_null( $last_run ) || empty( $last_run->timestamp ) || REQUEST_TIME - $last_run['timestamp'] > $frequency ) {
    WDG_Support_Monitor::get_instance()->update( FALSE );
  }
}