<?php
/**
 * @file Module
 * @author Web Development Group (WDG) <https://www.webdevelopmentgroup.com>
 */

/**
 * Implements hook_cron().
 */
function wdg_support_monitor_cron() {
  $frequency = 60 * 60 * 12; // 12 hours

  $wdg_support_monitor = WDG_Support_Monitor::get_instance();

  $last_run = $wdg_support_monitor->get_last_run();
  if ( is_null( $last_run ) || empty( $last_run->success) || empty( $last_run->timestamp ) || REQUEST_TIME - $last_run['timestamp'] > $frequency ) {
    $wdg_support_monitor->update( FALSE );
  }
}